<?php

namespace ContainerTyyZlrT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEcolesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EcolesController' shared autowired service.
     *
     * @return \App\Controller\EcolesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EcolesController.php';

        $container->services['App\\Controller\\EcolesController'] = $instance = new \App\Controller\EcolesController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\EcolesController', $container));

        return $instance;
    }
}
