<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7obhP4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7obhP4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7obhP4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7obhP4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7obhP4\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7obhP4',
    'container.build_id' => '7c2eff82',
    'container.build_time' => 1614440148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7obhP4');
