<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerENrkYyg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerENrkYyg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerENrkYyg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerENrkYyg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerENrkYyg\App_KernelDevDebugContainer([
    'container.build_hash' => 'ENrkYyg',
    'container.build_id' => '472152a4',
    'container.build_time' => 1614624723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerENrkYyg');
