<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerORdu2Z7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerORdu2Z7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerORdu2Z7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerORdu2Z7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerORdu2Z7\App_KernelDevDebugContainer([
    'container.build_hash' => 'ORdu2Z7',
    'container.build_id' => '423a6500',
    'container.build_time' => 1614442203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerORdu2Z7');
